version: "3.9"

services:
  frontend:
    image: jupyter-frontend:dev
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"   # host 3000 -> container 80 (nginx)
    depends_on:
      - backend

  backend:
    image: jupyter-backend:dev
    build:
      context: ./server
      dockerfile: ../docker/Dockerfile.api
    environment:
      - PORT=5000
    depends_on:
      - jupyter

  jupyter:
    image: jupyter-singleuser:dev
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
