apiVersion: apps/v1
kind: Deployment
metadata:
  name: colab-api
  namespace: jhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colab-api
  template:
    metadata:
      labels:
        app: colab-api
    spec:
      containers:
      - name: api
        image: jupyter-api:dev
        env:
        - name: JUPYTER_BASE
          value: "http://proxy-public:80" # when JupyterHub exposes proxy
        - name: SECRET_TOKEN
          value: "devtoken"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: colab-api
  namespace: jhub
spec:
  selector:
    app: colab-api
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
