apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colab-ingress
  namespace: jhub
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: colab.local
      http:
        paths:
          - path: /jupyter
            pathType: Prefix
            backend:
              service:
                name: colab-api
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: colab-frontend
                port:
                  number: 80
